### ISSUE TITLE
0 bytes 2d dataset

### ISSUE THREAD

**Issue by dkssudgktpdydn** [jaggbow/magnet#2]
Hello, I would like to download your code and dataset to replicate the research.

However, for the 2D dataset, most of the data files in the download link have a size of 0, making it impossible to reproduce. 

Is it possible for you to upload the data?

Thanks

**Comment by jaggbow** [comment]
Thanks for your first issue @dkssudgktpdydn !

Indeed, the 2D dataset seems unsynced, it is too big to fit in the limited storage. I'll move it elsewhere and update the link. Thanks again for pointing it out :)

**Comment by jaggbow** [comment]
I have just updated the link towards the dataset in the readme which now rests in the google drive.
